//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalHeroCompany.Models
{
    using System;
    using System.Collections.Generic;

    public class Hero
    {
        public System.Guid Id
        {
            get; set;
        } = Guid.NewGuid();
        public string Name
        {
            get;set;
        }
        public string Ability
        {
            get;set;
        }
        public DateTime TrainBeginning
        {
            get;set;
        }= DateTime.Now;
        public string SuitColors
        {
            get;set;
        }
        public int StartingPower
        {
            get;set;
        }
        public int CurrentPower
        {
            get;set;
        }
        public Guid TrainerId
        {
            get;set;
        }
        public int TrainCount
        {
            get; set;
        } = 0;



    }
}
