//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalHeroCompany.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;

    public class Trainer
    {
        public System.Guid Id
        {
            get;set;
        }= Guid.NewGuid();
        public string Email
        {
            get;set;
        }
        public string Password
        {
            get;set;
        }
        public string FullName
        {
            get;set;
        }
        public System.DateTime CreatedDate { get; set; } = new System.DateTime();
        



    }
}
